# Generated by Django 5.0.4 on 2024-06-16 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0002_alter_productocatalogo_precio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productocatalogo",
            name="precio",
        ),
    ]
