# Generated by Django 5.0.4 on 2024-05-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiar_producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='horario',
            field=models.CharField(choices=[('9:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM')], default=' ', max_length=5),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('realizado', 'Realizado'), ('ausente', 'Ausente')], default='pendiente', max_length=10),
        ),
    ]
