# Generated by Django 5.0.4 on 2024-05-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiar_producto', '0002_intercambio_horario_alter_intercambio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'lunes'), ('Martes', 'martes'), ('Miercoles', 'miercoles'), ('Jueves', 'jueves'), ('Viernes', 'viernes')], default=' ', max_length=20),
        ),
    ]
