# Generated by Django 5.0.4 on 2024-05-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiar_producto', '0004_alter_intercambio_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='horario',
            field=models.IntegerField(),
        ),
    ]
