# Generated by Django 5.0.4 on 2024-05-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiar_producto', '0005_alter_intercambio_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='dia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
