# Generated by Django 5.0.4 on 2024-07-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiar_producto', '0010_venta_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='sucursal',
        ),
    ]
