# Generated by Django 5.0.4 on 2024-07-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_sucursales', '0003_alter_perfilempleado_sucursal'),
        ('intercambiar_producto', '0011_remove_venta_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_sucursales.sucursal'),
        ),
    ]
