# Generated by Django 5.0.4 on 2024-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios', '0002_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
