# Generated by Django 5.0.4 on 2024-06-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios', '0003_servicio_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
