# Generated by Django 5.0.4 on 2024-06-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_de_servicios", "0004_alter_servicio_monto"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
