# Generated by Django 5.0.4 on 2024-06-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios', '0007_remove_tarjeta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.CharField(max_length=19),
        ),
    ]
