# Generated by Django 5.0.4 on 2024-06-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios', '0008_alter_tarjeta_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='año_vencimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='mes_vencimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
