# Generated by Django 5.0.4 on 2024-06-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios', '0009_remove_tarjeta_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='servicio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
