# Generated by Django 5.0.4 on 2024-07-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_de_servicios",
            "0010_remove_servicio_monto_remove_servicio_sucursal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="fechaFin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
