# Generated by Django 5.0.4 on 2024-05-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "nombre",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("ciudad", models.CharField(max_length=200)),
            ],
        ),
    ]
