# Generated by Django 5.0.4 on 2024-05-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_de_sucursales", "0002_perfilempleado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilempleado",
            name="sucursal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion_de_sucursales.sucursal",
            ),
        ),
    ]
