# Generated by Django 5.0.4 on 2024-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_de_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilcliente",
            name="monto_disponible",
            field=models.IntegerField(default=3000),
        ),
    ]
