# Generated by Django 5.0.4 on 2024-05-05 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=100)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                (
                    "horario_disponibilidad",
                    models.CharField(blank=True, max_length=100),
                ),
                ("sucursal", models.CharField(blank=True, max_length=100)),
                ("imagen_principal", models.ImageField(upload_to="imagenes/")),
                (
                    "imagen_extra1",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "imagen_extra2",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "imagen_extra3",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
