# Generated by Django 5.0.4 on 2024-05-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_productos", "0002_alter_producto_imagen_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
