# Generated by Django 5.0.4 on 2024-05-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_productos", "0003_producto_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="horario_disponibilidad",
            new_name="horario_fin",
        ),
        migrations.AddField(
            model_name="producto",
            name="horario_inicio",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
