# Generated by Django 5.0.4 on 2024-05-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mis_productos",
            "0004_rename_horario_disponibilidad_producto_horario_fin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producto",
            name="horario_fin",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producto",
            name="horario_inicio",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen_principal",
            field=models.ImageField(upload_to="imagenes/"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sucursal",
            field=models.CharField(max_length=100),
        ),
    ]
