# Generated by Django 5.0.4 on 2024-05-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mis_productos",
            "0005_alter_producto_categoria_alter_producto_estado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="dias",
            field=models.CharField(default="", max_length=100),
        ),
    ]
