# Generated by Django 5.0.4 on 2024-05-13 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_sucursales', '0003_alter_perfilempleado_sucursal'),
        ('mis_productos', '0006_producto_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_de_sucursales.sucursal'),
        ),
    ]
