# Generated by Django 5.0.4 on 2024-05-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_productos', '0007_alter_producto_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='dias',
        ),
        migrations.AddField(
            model_name='producto',
            name='dias',
            field=models.ManyToManyField(to='mis_productos.dia'),
        ),
    ]
