# Generated by Django 5.0.4 on 2024-05-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_productos', '0008_dia_remove_producto_dias_producto_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='dias',
        ),
        migrations.AddField(
            model_name='producto',
            name='dias',
            field=models.CharField(default='', max_length=100),
        ),
    ]
