# Generated by Django 5.0.4 on 2024-06-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_productos", "0010_alter_producto_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="slug",
        ),
        migrations.AddField(
            model_name="producto",
            name="visible",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
