# Generated by Django 5.0.4 on 2024-06-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_productos", "0011_remove_producto_slug_producto_visible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="visible",
        ),
        migrations.AddField(
            model_name="producto",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
